### PR TITLE
OOP school library: decorate a class PR

### PR DESCRIPTION
**Pull request by federicaulzurrun**
For this project I:

- Created decorator which inheritance from Nameable.
     - The decorator file contains:
            - Capitalize decorator
            - Trimmer decorator
- Created nameable class.
- Created test cases file.

### CODE REVIEW

**Review by 1GORDON — CHANGES_REQUESTED** [review]
##
## Hi @federicaulzurrun ✋

Good job so far!

## Highlights!
- Capitalised a class✔️ 
- Trimmed a class ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly fix the broken issues link to make your readme file more professional.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by federicaulzurrun** [comment]
@1GORDON hi! thanks for your time, can you tell me which links are not working?

**Comment by 1GORDON** [comment]
Hello @federicaulzurrun ✋

- [ ] It is the issues link in your readme file

**Comment by federicaulzurrun** [comment]
@1GORDON I already fixed it! thanks! I'm waiting for the new review

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @federicaulzurrun        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯



## Highlights   
- Good use of GitHub features ✔️  
- Nice work with the setup✔️    
  
# Required Changes  🌵  

- [ ] Since you don't have issues in the project, kindly use the right issues path as suggested by the last reviewer which is this [https://github.com/federicaulzurrun/SchoolLibrary/issues](https://github.com/federicaulzurrun/SchoolLibrary/issues)

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).










https://github.com/federicaulzurrun/SchoolLibrary/issues

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @federicaulzurrun        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯



## Highlights   
- Good use of GitHub features ✔️  
- Nice work with the setup✔️    
  
# Required Changes  🌵  

- [ ] Since you don't have issues in the project, kindly use the right issues path as suggested by the last reviewer which is this [https://github.com/federicaulzurrun/SchoolLibrary/issues](https://github.com/federicaulzurrun/SchoolLibrary/issues)

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).










https://github.com/federicaulzurrun/SchoolLibrary/issues

**Comment by federicaulzurrun** [comment]
@Shedrack-Sunday I'm sorry I still don't
Captura de Pantalla 2023-06-28 a la(s) 22 58 48
 get it, because if I click on issues the page is the one from that link

**Comment by federicaulzurrun** [comment]
@Shedrack-Sunday I'm sorry I still don't get it, if I
Captura de Pantalla 2023-06-28 a la(s) 23 00 51
 click on issues it goes to the link suggested

**Comment by federicaulzurrun** [comment]
@Shedrack-Sunday should i change it to this?
Captura de Pantalla 2023-06-28 a la(s) 23 02 40

**Comment by Shedrack-Sunday** [comment]
> @Shedrack-Sunday should i change it to this? Captura de Pantalla 2023-06-28 a la(s) 23 02 40

Yes please

**Review by brainconnect93 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @federicaulzurrun, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 




## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- `Namable` class with a method 'correct_name' rasing an error✔️
- `Person` class inherits from `Nameable` class
- `Decorator` class inherits from Namable.
- Has `CapitalizeDecorator` class
- Has `TrimmerDecorator` class
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
